import Link from "next/link";
import {notFound} from "next/navigation";
import {ProgramCard} from "@/components/program-card";
import {programs} from "@/lib/demo-data";
export function generateStaticParams(){return programs.map(p=>({slug:p.slug}))}
export default async function ProgramPage({params}:{params:Promise<{slug:string}>}){
 const{slug}=await params; const p=programs.find(x=>x.slug===slug); if(!p)notFound();
 const related=programs.filter(x=>x.slug!==p.slug).slice(0,2);
 return <main className="page-shell"><div className="container"><Link href="/programs" className="back-link">→ بازگشت به برنامه‌ها</Link><div className="program-detail"><div className="detail-main"><div className="detail-badge">{p.format} · {p.city}</div><h1>{p.title}</h1><p className="lead">{p.description}</p><div className="detail-meta"><div><span>گروه سنی</span><strong>{p.age}</strong></div><div><span>مدت</span><strong>{p.duration}</strong></div><div><span>ظرفیت</span><strong>{p.capacity}</strong></div><div><span>وضعیت</span><strong>{p.status}</strong></div></div><section className="detail-copy"><h2>چرا این برنامه؟</h2><p>{p.longDescription}</p><h2>آنچه تجربه می‌کنی</h2><ul>{p.outcomes.map(x=><li key={x}>{x}</li>)}</ul></section></div><aside className="detail-aside"><div className="registration-card"><span className="mini-label">ثبت‌نام</span><strong>{p.status}</strong><p>بعد از ورود، اطلاعاتت ذخیره می‌شود و وضعیت ثبت‌نام را از «مسیر من» دنبال می‌کنی.</p><Link className="button button-primary button-full" href="/login">ورود و ادامه ثبت‌نام</Link><span className="helper">اتصال فرم نهایی به داده واقعی Supabase پس از تطبیق schema موجود فعال می‌شود.</span></div></aside></div><section className="related-section"><div className="section-row"><h2>قدم‌های بعدی</h2><Link href="/programs">دیدن همه ←</Link></div><div className="program-grid">{related.map(x=><ProgramCard key={x.slug} program={x}/>)}</div></section></div></main>;
}