"use server";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import type { Database } from "@/lib/supabase/database.types";
type Role=Database["public"]["Enums"]["app_role"];type ProgramStatus=Database["public"]["Enums"]["program_status"];type RegistrationStatus=Database["public"]["Enums"]["registration_status"];
function v(fd:FormData,k:string){const x=fd.get(k);return typeof x==="string"?x.trim():"";}
function n(fd:FormData,k:string){const x=v(fd,k);if(!x)return null;const y=Number(x);return Number.isFinite(y)?y:null;}
function d(fd:FormData,k:string){const x=v(fd,k);if(!x)return null;const y=new Date(x);return Number.isNaN(y.getTime())?null:y.toISOString();}
async function requireRole(roles:Role[]){const supabase=await createClient();const {data}=await supabase.auth.getClaims();if(!data?.claims?.sub)redirect("/login?next=/admin");const userId=String(data.claims.sub);const {data:allowed,error}=await supabase.rpc("has_any_role",{required_roles:roles});if(error||!allowed)redirect("/dashboard");return{supabase,userId};}
export async function createProgram(fd:FormData){const {supabase,userId}=await requireRole(["super_admin","program_manager"]);const title=v(fd,"title"),slug=v(fd,"slug").toLowerCase(),status=v(fd,"status") as ProgramStatus;const valid:ProgramStatus[]=["draft","published","registration_closed","running"];if(!title||!/^[a-z0-9-]+$/.test(slug)||!valid.includes(status))throw new Error("invalid_program_payload");const {data,error}=await supabase.from("programs").insert({title,slug,status,program_type:v(fd,"program_type")||"training",summary:v(fd,"summary")||null,description:v(fd,"description")||null,audience_min_age:n(fd,"min_age"),audience_max_age:n(fd,"max_age"),capacity:n(fd,"capacity"),city:v(fd,"city")||null,location_name:v(fd,"location_name")||null,start_at:d(fd,"start_at"),end_at:d(fd,"end_at"),registration_open_at:d(fd,"registration_open_at"),registration_close_at:d(fd,"registration_close_at"),published_at:status==="published"?new Date().toISOString():null,created_by:userId}).select("id").single();if(error)throw new Error(error.message);await supabase.from("audit_logs").insert({actor_user_id:userId,action:"program.create",entity_type:"program",entity_id:data.id,metadata:{title,slug}});redirect("/admin/programs");}
const registrationStatuses:RegistrationStatus[]=["pending","confirmed","waitlisted","cancelled","rejected","completed"];
export async function updateRegistrationStatus(fd:FormData){const {supabase,userId}=await requireRole(["super_admin","program_manager","crm_manager"]);const id=v(fd,"registration_id"),status=v(fd,"status") as RegistrationStatus;if(!id||!registrationStatuses.includes(status))throw new Error("invalid_registration_update");const {data,error}=await supabase.from("registrations").update({status}).eq("id",id).select("program_id,user_id,status").single();if(error)throw new Error(error.message);await supabase.from("audit_logs").insert({actor_user_id:userId,action:"registration.status_change",entity_type:"registration",entity_id:id,metadata:{program_id:data.program_id,user_id:data.user_id,status}});redirect("/admin/registrations");}
export async function promoteWaitlist(fd:FormData){const {supabase}=await requireRole(["super_admin","program_manager","crm_manager"]);const programId=v(fd,"program_id");if(!programId)throw new Error("program_required");const {error}=await supabase.rpc("admin_promote_waitlist",{p_program_id:programId});if(error)throw new Error(error.message);redirect("/admin/registrations");}
