"use server";
import{revalidatePath}from"next/cache";import{createClient}from"@/lib/supabase/server";
async function staff(roles?:"all"|string[]){const s=await createClient();const{data}=await s.auth.getClaims();const uid=String(data?.claims?.sub||"");if(!uid)throw new Error("unauthorized");const{data:r}=await s.from("user_roles").select("role").eq("user_id",uid).maybeSingle();if(!r?.role||(roles!=="all"&&!roles.includes(r.role)))throw new Error("forbidden");return s}
const str=(f:FormData,k:string)=>String(f.get(k)||"").trim(), bool=(f:FormData,k:string)=>f.get(k)==="on";
export async function createReservation(_:unknown,f:FormData){const s=await createClient();const name=str(f,"name"),phone=str(f,"phone"),date=str(f,"date"),time=str(f,"time"),party=Number(f.get("party_size")||0),notes=str(f,"notes");if(name.length<2||phone.length<7||!date||!time||party<1||party>50)return{ok:false,message:"اطلاعات رزرو کامل نیست."};const at=new Date(`${date}T${time}:00`).toISOString();if(new Date(at)<=new Date())return{ok:false,message:"زمان رزرو باید در آینده باشد."};const{error}=await s.from("reservations").insert({name,phone,reservation_at:at,party_size:party,notes});if(error)return{ok:false,message:"ثبت رزرو انجام نشد."};await s.from("analytics_events").insert({event_type:"reservation_submit",metadata:{party_size:party}});revalidatePath("/");return{ok:true,message:"درخواست رزرو با موفقیت ثبت شد."}}
export async function trackEvent(type:string,id?:string){const s=await createClient();await s.from("analytics_events").insert({event_type:type,entity_id:id||null})}
export async function bootstrapFirstAdmin(){const s=await createClient();const{data}=await s.auth.getClaims();if(!data?.claims?.sub)return{ok:false,message:"ابتدا وارد شوید."};const{data:r,error}=await s.rpc("bootstrap_first_admin");if(error)return{ok:false,message:"راه‌اندازی مدیر اولیه انجام نشد."};return{ok:Boolean(r),message:r?"حساب شما مدیر ارشد شد.":"قبلاً مدیر اصلی ایجاد شده است."}}

export async function saveSettings(f:FormData){const s=await staff(["super_admin","manager"]);const payload={name:str(f,"name"),name_en:str(f,"name_en"),tagline:str(f,"tagline"),tagline_en:str(f,"tagline_en"),description:str(f,"description"),description_en:str(f,"description_en"),phone:str(f,"phone"),whatsapp:str(f,"whatsapp"),email:str(f,"email"),address:str(f,"address"),address_en:str(f,"address_en"),maps_url:str(f,"maps_url"),directions_url:str(f,"directions_url"),reservation_notes:str(f,"reservation_notes"),default_language:str(f,"default_language"),currency_code:str(f,"currency_code"),currency_symbol:str(f,"currency_symbol"),currency_position:str(f,"currency_position"),hours:JSON.parse(str(f,"hours")||"{}")};const{error}=await s.from("restaurant_settings").update(payload).eq("id","00000000-0000-0000-0000-000000000001");if(error)throw new Error(error.message);revalidatePath("/");revalidatePath("/admin/settings")}
export async function saveTheme(f:FormData){const s=await staff(["super_admin"]);const p={primary_color:str(f,"primary_color"),secondary_color:str(f,"secondary_color"),accent_color:str(f,"accent_color"),dark_background:str(f,"dark_background"),dark_surface:str(f,"dark_surface"),dark_text:str(f,"dark_text"),light_background:str(f,"light_background"),light_surface:str(f,"light_surface"),light_text:str(f,"light_text"),muted_text:str(f,"muted_text"),font_family:str(f,"font_family"),radius_px:Number(f.get("radius_px")),shadow_strength:Number(f.get("shadow_strength")),button_style:str(f,"button_style"),default_mode:str(f,"default_mode")};const{error}=await s.from("theme_settings").update(p).eq("id","00000000-0000-0000-0000-000000000002");if(error)throw new Error(error.message);revalidatePath("/");revalidatePath("/admin/theme")}
export async function saveSection(f:FormData){const s=await staff(["super_admin","editor"]);const id=str(f,"id");const p={title:str(f,"title"),title_en:str(f,"title_en"),subtitle:str(f,"subtitle"),subtitle_en:str(f,"subtitle_en"),body:str(f,"body"),body_en:str(f,"body_en"),enabled:bool(f,"enabled"),settings:JSON.parse(str(f,"settings")||"{}")};const{error}=await s.from("site_sections").update(p).eq("id",id);if(error)throw new Error(error.message);revalidatePath("/");revalidatePath("/admin/content")}
export async function createCategory(f:FormData){const s=await staff("all");const{error}=await s.from("menu_categories").insert({name:str(f,"name"),name_en:str(f,"name_en"),description:str(f,"description"),description_en:str(f,"description_en"),icon:str(f,"icon")||"✦",sort_order:Number(f.get("sort_order")||100)});if(error)throw new Error(error.message);revalidatePath("/menu");revalidatePath("/admin/menu")}
export async function updateCategory(f:FormData){const s=await staff("all");const{error}=await s.from("menu_categories").update({name:str(f,"name"),name_en:str(f,"name_en"),description:str(f,"description"),description_en:str(f,"description_en"),icon:str(f,"icon"),is_active:bool(f,"is_active")}).eq("id",str(f,"id"));if(error)throw new Error(error.message);revalidatePath("/menu");revalidatePath("/admin/menu")}
export async function deleteCategory(f:FormData){const s=await staff("all");const id=str(f,"id");const{count}=await s.from("menu_items").select("id",{count:"exact",head:true}).eq("category_id",id).is("deleted_at",null);if((count||0)>0)throw new Error("ابتدا غذاهای این دسته را جابه‌جا یا حذف کنید.");const{error}=await s.from("menu_categories").update({deleted_at:new Date().toISOString(),is_active:false}).eq("id",id);if(error)throw new Error(error.message);revalidatePath("/menu");revalidatePath("/admin/menu")}
export async function createItem(f:FormData){const s=await staff("all");const p={category_id:str(f,"category_id"),name:str(f,"name"),name_en:str(f,"name_en"),description:str(f,"description"),description_en:str(f,"description_en"),ingredients:str(f,"ingredients"),ingredients_en:str(f,"ingredients_en"),allergens:str(f,"allergens").split(",").map(x=>x.trim()).filter(Boolean),tags:str(f,"tags").split(",").map(x=>x.trim()).filter(Boolean),price:Number(f.get("price")||0),old_price:f.get("old_price")?Number(f.get("old_price")):null,sort_order:Number(f.get("sort_order")||100),is_available:bool(f,"is_available"),is_special:bool(f,"is_special"),is_popular:bool(f,"is_popular"),is_new:bool(f,"is_new"),is_vegetarian:bool(f,"is_vegetarian"),is_vegan:bool(f,"is_vegan"),is_spicy:bool(f,"is_spicy")};const{error}=await s.from("menu_items").insert(p);if(error)throw new Error(error.message);revalidatePath("/menu");revalidatePath("/admin/menu")}
export async function updateItem(f:FormData){const s=await staff("all");const id=str(f,"id");const{error}=await s.from("menu_items").update({category_id:str(f,"category_id"),name:str(f,"name"),name_en:str(f,"name_en"),description:str(f,"description"),description_en:str(f,"description_en"),ingredients:str(f,"ingredients"),ingredients_en:str(f,"ingredients_en"),allergens:str(f,"allergens").split(",").map(x=>x.trim()).filter(Boolean),tags:str(f,"tags").split(",").map(x=>x.trim()).filter(Boolean),price:Number(f.get("price")||0),old_price:f.get("old_price")?Number(f.get("old_price")):null,is_available:bool(f,"is_available"),is_special:bool(f,"is_special"),is_popular:bool(f,"is_popular"),is_new:bool(f,"is_new"),is_vegetarian:bool(f,"is_vegetarian"),is_vegan:bool(f,"is_vegan"),is_spicy:bool(f,"is_spicy")}).eq("id",id);if(error)throw new Error(error.message);revalidatePath("/menu");revalidatePath("/admin/menu")}
export async function deleteItem(f:FormData){const s=await staff("all");const{error}=await s.from("menu_items").update({deleted_at:new Date().toISOString(),is_available:false}).eq("id",str(f,"id"));if(error)throw new Error(error.message);revalidatePath("/menu");revalidatePath("/admin/menu")}
export async function updateReservation(f:FormData){const s=await staff(["super_admin","manager"]);const{error}=await s.from("reservations").update({status:str(f,"status")}).eq("id",str(f,"id"));if(error)throw new Error(error.message);revalidatePath("/admin/reservations")}
export async function deleteReservation(f:FormData){const s=await staff(["super_admin","manager"]);const{error}=await s.from("reservations").delete().eq("id",str(f,"id"));if(error)throw new Error(error.message);revalidatePath("/admin/reservations")}
export async function deleteMedia(f:FormData){const s=await staff("all");const id=str(f,"id");const{data:m}=await s.from("media").select("file_path").eq("id",id).single();if(m?.file_path)await s.storage.from("restaurant-media").remove([m.file_path]);const{error}=await s.from("media").update({deleted_at:new Date().toISOString()}).eq("id",id);if(error)throw new Error(error.message);revalidatePath("/admin/media");revalidatePath("/")}
export async function saveSeo(f:FormData){const s=await staff(["super_admin"]);const{error}=await s.from("seo_settings").update({title:str(f,"title"),description:str(f,"description"),keywords:str(f,"keywords").split(",").map(x=>x.trim()).filter(Boolean),canonical_url:str(f,"canonical_url"),robots_index:bool(f,"robots_index"),robots_follow:bool(f,"robots_follow")}).eq("id","00000000-0000-0000-0000-000000000003");if(error)throw new Error(error.message);revalidatePath("/");revalidatePath("/admin/seo")}
export async function saveRole(f:FormData){const s=await staff(["super_admin"]);const{error}=await s.from("user_roles").upsert({user_id:str(f,"user_id"),role:str(f,"role")});if(error)throw new Error(error.message);revalidatePath("/admin/roles")}
export async function saveSocial(f:FormData){const s=await staff(["super_admin","manager"]);const{error}=await s.from("social_links").update({url:str(f,"url"),is_enabled:bool(f,"is_enabled")}).eq("id",str(f,"id"));if(error)throw new Error(error.message);revalidatePath("/")}
export async function saveNav(f:FormData){const s=await staff(["super_admin","manager"]);const{error}=await s.from("navigation_items").update({label:str(f,"label"),label_en:str(f,"label_en"),href:str(f,"href"),is_enabled:bool(f,"is_enabled")}).eq("id",str(f,"id"));if(error)throw new Error(error.message);revalidatePath("/")}
export async function createOffer(f:FormData){const s=await staff("all");const{error}=await s.from("special_offers").insert({title:str(f,"title"),title_en:str(f,"title_en"),description:str(f,"description"),description_en:str(f,"description_en"),old_price:f.get("old_price")?Number(f.get("old_price")):null,new_price:f.get("new_price")?Number(f.get("new_price")):null,starts_at:new Date(str(f,"starts_at")).toISOString(),ends_at:new Date(str(f,"ends_at")).toISOString(),is_active:bool(f,"is_active")});if(error)throw new Error(error.message);revalidatePath("/");revalidatePath("/admin/offers")}
export async function deleteOffer(f:FormData){const s=await staff("all");const{error}=await s.from("special_offers").update({is_active:false}).eq("id",str(f,"id"));if(error)throw new Error(error.message);revalidatePath("/");revalidatePath("/admin/offers")}