"use client";
import{useState}from"react";import Link from"next/link";import type{Settings,Theme,Section,NavItem,Social,Category,MenuItem,Gallery,Offer,Media,Lang}from"@/lib/types";import{money,txt}from"@/lib/utils";import{ReservationForm}from"@/components/reservation-form";
type P={settings:Settings;theme:Theme;sections:Section[];nav:NavItem[];social:Social[];categories:Category[];items:MenuItem[];gallery:Gallery[];offers:Offer[];media:Media[];};
export function Home({data}:{data:P}){const[l,setL]=useState<Lang>("fa");const[mode,setMode]=useState<"dark"|"light">(data.theme.default_mode);const S=(k:string)=>data.sections.find(x=>x.section_key===k&&x.enabled);const hero=S("hero"),about=S("about"),featured=S("featured"),offers=S("offers"),gallery=S("gallery"),reservation=S("reservation"),contact=S("contact"),footer=S("footer");const items=data.items.filter(x=>x.is_available&&((x.is_special||x.is_popular)||x.category_id===data.categories[0]?.id)).slice(0,6);
const dir=l==="fa"?"rtl":"ltr";const img=(id:string|null)=>data.media.find(x=>x.id===id)?.public_url||"";const name=txt(data.settings.name,data.settings.name_en,l);return <div dir={dir} data-mode={mode} className="site" style={{"--gold":data.theme.primary_color,"--gold2":data.theme.accent_color,"--bg":mode==="dark"?data.theme.dark_background:data.theme.light_background,"--surface":mode==="dark"?data.theme.dark_surface:data.theme.light_surface,"--fg":mode==="dark"?data.theme.dark_text:data.theme.light_text,"--muted":data.theme.muted_text,"--radius":`${data.theme.radius_px}px`,"--font":data.theme.font_family} as React.CSSProperties}>
<header className="site-header"><div className="shell nav"><Link className="brand" href="/"><span className="brand-mark">{data.settings.logo_media_id&&img(data.settings.logo_media_id)?<img src={img(data.settings.logo_media_id)} alt={name}/>: "N"}</span><span>{name}</span></Link><nav>{data.nav.map(n=><a key={n.id} href={n.href}>{txt(n.label,n.label_en,l)}</a>)}</nav><div className="nav-tools"><Link href="/menu" className="btn gold small">{l==="fa"?"منوی دیجیتال":"Digital Menu"}</Link><button className="icon-btn" onClick={()=>setMode(mode==="dark"?"light":"dark")} aria-label="Toggle theme">◐</button><button className="lang" onClick={()=>setL(l==="fa"?"en":"fa")}>{l==="fa"?"EN":"فا"}</button></div></div></header>
<main>
{hero&&<section className="hero-home" style={{minHeight:String((hero.settings.height as string)||"86vh")}}><div className="hero-bg">{img(hero.image_media_id)&&<img src={img(hero.image_media_id)} alt=""/>}</div><div className="hero-overlay" style={{opacity:Number(hero.settings.overlay??.58)}}></div><div className="shell hero-inner"><span className="kicker">NOIR · {l==="fa"?"رستوران معاصر":"CONTEMPORARY DINING"}</span><h1>{txt(hero.title,hero.title_en,l)}</h1><p>{txt(hero.subtitle,hero.subtitle_en,l)}</p><div className="hero-actions"><Link href="/menu" className="btn gold">{l==="fa"?"مشاهده منو":"View menu"}</Link>{reservation&&<a href="#reservation" className="btn ghost">{txt(reservation.title,reservation.title_en,l)}</a>}</div></div></section>}
{about&&<section id="about" className="section split"><div><span className="kicker">01 · NOIR</span><h2>{txt(about.title,about.title_en,l)}</h2><p className="lead">{txt(about.subtitle,about.subtitle_en,l)}</p><p>{txt(about.body,about.body_en,l)}</p></div><div className="feature-frame">{img(about.image_media_id)?<img src={img(about.image_media_id)} alt={txt(about.title,about.title_en,l)} loading="lazy"/>:<div className="frame-empty"><span>NOIR</span></div>}</div></section>}
{featured&&<section className="section" id="featured"><div className="section-head"><div><span className="kicker">02 · SIGNATURE</span><h2>{txt(featured.title,featured.title_en,l)}</h2><p>{txt(featured.subtitle,featured.subtitle_en,l)}</p></div><Link href="/menu" className="text-link">{l==="fa"?"تمام منو":"Full menu"} ↗</Link></div><div className="dish-grid">{items.map(i=><article className="dish-card" key={i.id}><div className="dish-image">{i.media?.public_url?<img src={i.media.public_url} alt={txt(i.name,i.name_en,l)} loading="lazy"/>:<div className="no-image">NOIR</div>}<div className="dish-flags">{i.is_special&&<span>Special</span>}{i.is_popular&&<span>Popular</span>}{i.is_new&&<span>New</span>}</div></div><div className="dish-copy"><div><h3>{txt(i.name,i.name_en,l)}</h3><p>{txt(i.description,i.description_en,l)}</p></div><strong>{money(i.price,data.settings.currency_code,data.settings.currency_symbol,data.settings.currency_position)}</strong></div></article>)}</div></section>}
{offers&&data.offers.length>0&&<section className="section offer-band" id="offers"><div className="shell"><span className="kicker">03 · LIMITED</span><h2>{txt(offers.title,offers.title_en,l)}</h2><p>{txt(offers.subtitle,offers.subtitle_en,l)}</p><div className="offer-grid">{data.offers.map(o=><article className="offer-card" key={o.id}><div><h3>{txt(o.title,o.title_en,l)}</h3><p>{txt(o.description,o.description_en,l)}</p></div><div className="offer-price">{o.old_price&&<s>{money(o.old_price,data.settings.currency_code,data.settings.currency_symbol,data.settings.currency_position)}</s>}<strong>{o.new_price&&money(o.new_price,data.settings.currency_code,data.settings.currency_symbol,data.settings.currency_position)}</strong></div></article>)}</div></div></section>}
{gallery&&<section className="section" id="gallery"><div className="section-head"><div><span className="kicker">04 · ATMOSPHERE</span><h2>{txt(gallery.title,gallery.title_en,l)}</h2><p>{txt(gallery.subtitle,gallery.subtitle_en,l)}</p></div></div><div className="gallery-grid">{data.gallery.slice(0,8).map(g=><figure key={g.id}>{g.media?.public_url?<img src={g.media.public_url} alt={g.media.alt_text||g.title} loading="lazy"/>:<div className="no-image">NOIR</div>}<figcaption>{g.title}</figcaption></figure>)}</div></section>}
{reservation&&<section id="reservation" className="section reservation-section"><div className="reservation-wrap"><div><span className="kicker">05 · RESERVATION</span><h2>{txt(reservation.title,reservation.title_en,l)}</h2><p className="lead">{txt(reservation.subtitle,reservation.subtitle_en,l)}</p>{data.settings.reservation_notes&&<p className="small">{data.settings.reservation_notes}</p>}</div><ReservationForm/></div></section>}
{contact&&<section id="contact" className="section contact-section"><div><span className="kicker">06 · CONTACT</span><h2>{txt(contact.title,contact.title_en,l)}</h2><p>{txt(contact.subtitle,contact.subtitle_en,l)}</p></div><div className="contact-grid"><a onClick={()=>fetch("/api/analytics",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({event_type:"contact_click"})})} href={data.settings.phone?`tel:${data.settings.phone.replace(/\s/g,"") } `:""}><span>Phone</span><strong>{data.settings.phone||"—"}</strong></a><a href={data.settings.whatsapp?`https://wa.me/${data.settings.whatsapp.replace(/\D/g,"")}`:""} target="_blank" rel="noreferrer"><span>WhatsApp</span><strong>{data.settings.whatsapp||"—"}</strong></a><a href={data.settings.maps_url||"#"} target="_blank" rel="noreferrer"><span>Maps</span><strong>{data.settings.address||"—"}</strong></a><div><span>Hours</span><strong>{Object.entries(data.settings.hours||{}).slice(0,3).map(([d,h])=><em key={d}>{d}: {h}</em>)}</strong></div></div></section>}
</main>
<footer className="site-footer"><div className="shell footer-grid"><div><div className="brand"><span className="brand-mark">N</span><span>{name}</span></div><p>{txt(data.settings.tagline,data.settings.tagline_en,l)}</p></div><div><span className="kicker">SOCIAL</span>{data.social.map(s=><a key={s.id} href={s.url||"#"} target="_blank" rel="noreferrer">{s.label} ↗</a>)}</div><div><span className="kicker">NAV</span><a href="/menu">{l==="fa"?"منوی دیجیتال":"Digital Menu"}</a><a href="#reservation">{l==="fa"?"رزرو میز":"Reservation"}</a></div></div>{footer&&<div className="copyright">{txt(footer.body,footer.body_en,l)}</div>}</footer>
</div>}