export type Role="super_admin"|"manager"|"editor";
export type Lang="fa"|"en";
export type ThemeMode="dark"|"light";
export interface Settings{ id:string; name:string; name_en:string; tagline:string; tagline_en:string; description:string; description_en:string; phone:string; whatsapp:string; email:string; address:string; address_en:string; hours:Record<string,string>; closed_days:string[]; maps_url:string; directions_url:string; reservation_notes:string; logo_media_id:string|null; favicon_media_id:string|null; default_language:Lang; currency_code:string; currency_symbol:string; currency_position:"before"|"after"; updated_at:string; }
export interface Theme{ id:string; primary_color:string; secondary_color:string; accent_color:string; dark_background:string; dark_surface:string; dark_text:string; light_background:string; light_surface:string; light_text:string; muted_text:string; font_family:string; radius_px:number; shadow_strength:number; button_style:"solid"|"outline"|"pill"; default_mode:ThemeMode; }
export interface Section{ id:string; section_key:string; title:string; title_en:string; subtitle:string; subtitle_en:string; body:string; body_en:string; image_media_id:string|null; mobile_image_media_id:string|null; enabled:boolean; sort_order:number; settings:Record<string,unknown>; }
export interface NavItem{ id:string; label:string; label_en:string; href:string; sort_order:number; is_enabled:boolean; }
export interface Social{ id:string; provider:string; label:string; url:string; is_enabled:boolean; sort_order:number; }
export interface Category{ id:string; name:string; name_en:string; description:string; description_en:string; media_id:string|null; icon:string; sort_order:number; is_active:boolean; deleted_at:string|null; }
export interface MenuItem{ id:string; category_id:string; name:string; name_en:string; description:string; description_en:string; ingredients:string; ingredients_en:string; allergens:string[]; tags:string[]; price:number; old_price:number|null; media_id:string|null; sort_order:number; is_available:boolean; is_special:boolean; is_popular:boolean; is_new:boolean; is_vegetarian:boolean; is_vegan:boolean; is_spicy:boolean; category?:Category; media?:Media; }
export interface Media{ id:string; file_path:string; public_url:string; filename:string; alt_text:string; mime_type:string; byte_size:number; width:number|null; height:number|null; created_at:string; }
export interface Gallery{ id:string; media_id:string; title:string; caption:string; sort_order:number; is_enabled:boolean; media?:Media; }
export interface Offer{ id:string; title:string; title_en:string; description:string; description_en:string; image_media_id:string|null; old_price:number|null; new_price:number|null; starts_at:string; ends_at:string; is_active:boolean; media?:Media; }
export interface Reservation{ id:string; name:string; phone:string; reservation_at:string; party_size:number; notes:string; status:"pending"|"confirmed"|"cancelled"|"completed"; created_at:string; }
export interface SEO{ id:string; title:string; description:string; keywords:string[]; og_image_media_id:string|null; canonical_url:string; robots_index:boolean; robots_follow:boolean; }