-- NOIR Restaurant reset. Replaces the previous application schema while preserving Supabase Auth users.
create extension if not exists pgcrypto;
do $$declare r record;begin
 for r in select n.nspname,c.relname,c.relkind from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind in('r','p','v','m','f','S')
 loop execute format('drop %s if exists public.%I cascade',case r.relkind when 'v' then 'view' when 'm' then 'materialized view' when 'S' then 'sequence' else 'table' end,r.relname);end loop;
end$$;
do $$declare r record;begin
 for r in select p.oid::regprocedure signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public'
 loop execute format('drop function if exists %s cascade',r.signature);end loop;
end$$;
do $$declare r record;begin
 for r in select t.typname from pg_type t join pg_namespace n on n.oid=t.typnamespace where n.nspname='public' and t.typtype='e'
 loop execute format('drop type if exists public.%I cascade',r.typname);end loop;
end$$;

drop schema if exists private cascade;create schema private;revoke all on schema private from public,anon,authenticated;
create type public.app_role as enum('super_admin','manager','editor');create type public.reservation_status as enum('pending','confirmed','cancelled','completed');

create table public.roles(id uuid primary key default gen_random_uuid(),slug public.app_role unique not null,name text not null,description text not null default '',created_at timestamptz not null default now());
create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,email text not null default '',display_name text not null default '',avatar_url text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.user_roles(user_id uuid primary key references auth.users(id) on delete cascade,role public.app_role not null,assigned_by uuid references auth.users(id),assigned_at timestamptz not null default now());
create table public.media(id uuid primary key default gen_random_uuid(),file_path text unique not null,public_url text not null,filename text not null,alt_text text not null default '',mime_type text not null default 'image/webp',byte_size bigint not null default 0,width integer,height integer,created_by uuid references auth.users(id),deleted_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());

create table public.restaurant_settings(id uuid primary key default '00000000-0000-0000-0000-000000000001',name text not null default 'رستوران نوآر',name_en text not null default 'NOIR',tagline text not null default 'طعم، فراتر از انتظار',tagline_en text not null default 'Taste beyond expectation',description text not null default '',description_en text not null default '',phone text not null default '',whatsapp text not null default '',email text not null default '',address text not null default '',address_en text not null default '',hours jsonb not null default '{}',closed_days text[] not null default '{}',maps_url text not null default '',directions_url text not null default '',reservation_notes text not null default '',logo_media_id uuid references public.media(id) on delete set null,favicon_media_id uuid references public.media(id) on delete set null,default_language text not null default 'fa' check(default_language in('fa','en')),currency_code text not null default 'IRR',currency_symbol text not null default '﷼',currency_position text not null default 'after' check(currency_position in('before','after')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.theme_settings(id uuid primary key default '00000000-0000-0000-0000-000000000002',primary_color text not null default '#D6B978',secondary_color text not null default '#1D1D1B',accent_color text not null default '#F0DFB2',dark_background text not null default '#0D0D0C',dark_surface text not null default '#171715',dark_text text not null default '#F6F1E7',light_background text not null default '#F6F1E7',light_surface text not null default '#FFFCF6',light_text text not null default '#191814',muted_text text not null default '#9B9588',font_family text not null default 'system-ui,sans-serif',radius_px int not null default 18,shadow_strength numeric not null default .22,button_style text not null default 'solid',default_mode text not null default 'dark',updated_at timestamptz not null default now());
create table public.site_sections(id uuid primary key default gen_random_uuid(),section_key text unique not null,title text not null default '',title_en text not null default '',subtitle text not null default '',subtitle_en text not null default '',body text not null default '',body_en text not null default '',image_media_id uuid references public.media(id) on delete set null,mobile_image_media_id uuid references public.media(id) on delete set null,enabled boolean not null default true,sort_order int not null default 0,settings jsonb not null default '{}',updated_at timestamptz not null default now());
create table public.navigation_items(id uuid primary key default gen_random_uuid(),label text not null,label_en text not null default '',href text not null,sort_order int not null default 0,is_enabled boolean not null default true,updated_at timestamptz not null default now());
create table public.social_links(id uuid primary key default gen_random_uuid(),provider text unique not null,label text not null,url text not null default '',is_enabled boolean not null default false,sort_order int not null default 0,updated_at timestamptz not null default now());
create table public.menu_categories(id uuid primary key default gen_random_uuid(),name text not null,name_en text not null default '',description text not null default '',description_en text not null default '',media_id uuid references public.media(id) on delete set null,icon text not null default '✦',sort_order int not null default 0,is_active boolean not null default true,deleted_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.menu_items(id uuid primary key default gen_random_uuid(),category_id uuid not null references public.menu_categories(id) on delete restrict,name text not null,name_en text not null default '',description text not null default '',description_en text not null default '',ingredients text not null default '',ingredients_en text not null default '',allergens text[] not null default '{}',tags text[] not null default '{}',price numeric(14,2) not null default 0,old_price numeric(14,2),media_id uuid references public.media(id) on delete set null,sort_order int not null default 0,is_available boolean not null default true,is_special boolean not null default false,is_popular boolean not null default false,is_new boolean not null default false,is_vegetarian boolean not null default false,is_vegan boolean not null default false,is_spicy boolean not null default false,deleted_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),constraint menu_old_price_check check(old_price is null or old_price>=price));
create table public.gallery_items(id uuid primary key default gen_random_uuid(),media_id uuid not null references public.media(id) on delete restrict,title text not null default '',caption text not null default '',sort_order int not null default 0,is_enabled boolean not null default true,deleted_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.special_offers(id uuid primary key default gen_random_uuid(),title text not null,title_en text not null default '',description text not null default '',description_en text not null default '',image_media_id uuid references public.media(id) on delete set null,old_price numeric(14,2),new_price numeric(14,2),starts_at timestamptz not null,ends_at timestamptz not null,is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),constraint offer_window_check check(ends_at>=starts_at));
create table public.reservations(id uuid primary key default gen_random_uuid(),name text not null,phone text not null,reservation_at timestamptz not null,party_size int not null check(party_size between 1 and 50),notes text not null default '',status public.reservation_status not null default 'pending',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.seo_settings(id uuid primary key default '00000000-0000-0000-0000-000000000003',title text not null default 'رستوران نوآر',description text not null default '',keywords text[] not null default '{}',og_image_media_id uuid references public.media(id) on delete set null,canonical_url text not null default '',robots_index boolean not null default true,robots_follow boolean not null default true,updated_at timestamptz not null default now());
create table public.analytics_events(id bigint generated always as identity primary key,event_type text not null,entity_id uuid,metadata jsonb not null default '{}',created_at timestamptz not null default now());
create table public.audit_logs(id bigint generated always as identity primary key,actor_user_id uuid references auth.users(id) on delete set null,action text not null,entity_type text not null,entity_id uuid,details jsonb not null default '{}',created_at timestamptz not null default now());

create index menu_categories_sort_idx on public.menu_categories(is_active,sort_order);create index menu_items_category_sort_idx on public.menu_items(category_id,deleted_at,sort_order);create index menu_items_flags_idx on public.menu_items(is_available,is_special,is_popular,is_new,is_vegetarian,is_vegan,is_spicy);create index media_deleted_created_idx on public.media(deleted_at,created_at desc);create index reservations_window_idx on public.reservations(reservation_at,status);create index analytics_event_time_idx on public.analytics_events(event_type,created_at desc);create index audit_entity_idx on public.audit_logs(entity_type,entity_id,created_at desc);

create function private.has_role(required_role text) returns boolean language sql stable security definer set search_path=public,pg_temp as $$select exists(select 1 from public.user_roles where user_id=(select auth.uid()) and role::text=required_role)$$;
create function private.has_any_role(required_roles text[]) returns boolean language sql stable security definer set search_path=public,pg_temp as $$select exists(select 1 from public.user_roles where user_id=(select auth.uid()) and role::text=any(required_roles))$$;
create function private.touch_updated_at() returns trigger language plpgsql as $$begin new.updated_at=now();return new;end$$;
create function private.audit_row_change() returns trigger language plpgsql security definer set search_path=public,pg_temp as $$declare o jsonb; n jsonb; eid uuid;begin o=case when tg_op in('UPDATE','DELETE') then to_jsonb(old) end;n=case when tg_op in('INSERT','UPDATE') then to_jsonb(new) end;eid=case when tg_table_name='user_roles' then (case when tg_op='DELETE' then o->>'user_id' else n->>'user_id' end)::uuid else (case when tg_op='DELETE' then o->>'id' else n->>'id' end)::uuid end;insert into public.audit_logs(actor_user_id,action,entity_type,entity_id,details)values(auth.uid(),lower(tg_op),tg_table_name,eid,jsonb_build_object('before',o,'after',n));return coalesce(new,old);end$$;
create function private.handle_new_user() returns trigger language plpgsql security definer set search_path=public,pg_temp as $$begin insert into public.profiles(id,email,display_name)values(new.id,coalesce(new.email,''),coalesce(new.raw_user_meta_data->>'full_name',split_part(coalesce(new.email,''),'@',1)))on conflict(id)do update set email=excluded.email;return new;end$$;
create function private.bootstrap_first_admin() returns boolean language plpgsql security definer set search_path=public,pg_temp as $$begin if auth.uid() is null then raise exception 'authentication_required';end if;perform pg_advisory_xact_lock(739921);if exists(select 1 from public.user_roles) then return false;end if;insert into public.user_roles(user_id,role,assigned_by)values(auth.uid(),'super_admin',auth.uid());return true;end$$;
create function public.bootstrap_first_admin() returns boolean language sql security invoker set search_path=public,private as $$select private.bootstrap_first_admin()$$;
revoke all on function private.has_role(text),private.has_any_role(text[]),private.touch_updated_at(),private.audit_row_change(),private.handle_new_user(),private.bootstrap_first_admin() from public,anon,authenticated;
revoke all on function public.bootstrap_first_admin() from public,anon;grant execute on function private.has_role(text),private.has_any_role(text[]) to authenticated;grant execute on function public.bootstrap_first_admin() to authenticated;
drop trigger if exists on_auth_user_created on auth.users;create trigger on_auth_user_created after insert on auth.users for each row execute function private.handle_new_user();

do $$declare t text;begin foreach t in array array['roles','profiles','user_roles','media','restaurant_settings','theme_settings','site_sections','navigation_items','social_links','menu_categories','menu_items','gallery_items','special_offers','reservations','seo_settings','analytics_events','audit_logs']loop execute format('alter table public.%I enable row level security',t);end loop;end$$;

create policy roles_read on public.roles for select to authenticated using(true);
create policy profiles_self_read on public.profiles for select to authenticated using(auth.uid()=id);create policy profiles_admin_read on public.profiles for select to authenticated using(private.has_role('super_admin'));
create policy profiles_self_update on public.profiles for update to authenticated using(auth.uid()=id) with check(auth.uid()=id);
create policy user_roles_self_read on public.user_roles for select to authenticated using(auth.uid()=user_id);create policy user_roles_super_admin_all on public.user_roles for all to authenticated using(private.has_role('super_admin')) with check(private.has_role('super_admin'));
create policy settings_public_read on public.restaurant_settings for select to anon,authenticated using(true);create policy settings_manage on public.restaurant_settings for all to authenticated using(private.has_any_role(array['super_admin','manager'])) with check(private.has_any_role(array['super_admin','manager']));
create policy theme_public_read on public.theme_settings for select to anon,authenticated using(true);create policy theme_manage on public.theme_settings for all to authenticated using(private.has_role('super_admin')) with check(private.has_role('super_admin'));
create policy sections_public_read on public.site_sections for select to anon,authenticated using(enabled);create policy sections_manage on public.site_sections for all to authenticated using(private.has_any_role(array['super_admin','editor'])) with check(private.has_any_role(array['super_admin','editor']));
create policy nav_public_read on public.navigation_items for select to anon,authenticated using(is_enabled);create policy nav_manage on public.navigation_items for all to authenticated using(private.has_any_role(array['super_admin','manager'])) with check(private.has_any_role(array['super_admin','manager']));
create policy social_public_read on public.social_links for select to anon,authenticated using(is_enabled);create policy social_manage on public.social_links for all to authenticated using(private.has_any_role(array['super_admin','manager'])) with check(private.has_any_role(array['super_admin','manager']));
create policy media_public_read on public.media for select to anon,authenticated using(deleted_at is null);create policy media_staff_all on public.media for all to authenticated using(private.has_any_role(array['super_admin','manager','editor'])) with check(private.has_any_role(array['super_admin','manager','editor']));
create policy cat_public_read on public.menu_categories for select to anon,authenticated using(is_active and deleted_at is null);create policy cat_staff_all on public.menu_categories for all to authenticated using(private.has_any_role(array['super_admin','manager','editor'])) with check(private.has_any_role(array['super_admin','manager','editor']));
create policy item_public_read on public.menu_items for select to anon,authenticated using(deleted_at is null and exists(select 1 from public.menu_categories c where c.id=category_id and c.is_active and c.deleted_at is null));create policy item_staff_all on public.menu_items for all to authenticated using(private.has_any_role(array['super_admin','manager','editor'])) with check(private.has_any_role(array['super_admin','manager','editor']));
create policy gallery_public_read on public.gallery_items for select to anon,authenticated using(is_enabled and deleted_at is null);create policy gallery_staff_all on public.gallery_items for all to authenticated using(private.has_any_role(array['super_admin','manager','editor'])) with check(private.has_any_role(array['super_admin','manager','editor']));
create policy offers_public_read on public.special_offers for select to anon,authenticated using(is_active and starts_at<=now() and ends_at>=now());create policy offers_staff_all on public.special_offers for all to authenticated using(private.has_any_role(array['super_admin','manager','editor'])) with check(private.has_any_role(array['super_admin','manager','editor']));
create policy reservation_public_insert on public.reservations for insert to anon,authenticated with check(reservation_at>=now() and char_length(trim(name)) between 2 and 120 and char_length(trim(phone)) between 7 and 30);
create policy reservation_staff_read on public.reservations for select to authenticated using(private.has_any_role(array['super_admin','manager']));create policy reservation_staff_update on public.reservations for update to authenticated using(private.has_any_role(array['super_admin','manager'])) with check(private.has_any_role(array['super_admin','manager']));create policy reservation_staff_delete on public.reservations for delete to authenticated using(private.has_any_role(array['super_admin','manager']));
create policy seo_public_read on public.seo_settings for select to anon,authenticated using(true);create policy seo_manage on public.seo_settings for all to authenticated using(private.has_role('super_admin')) with check(private.has_role('super_admin'));
create policy analytics_insert on public.analytics_events for insert to anon,authenticated with check(event_type in('page_view','menu_view','menu_item_view','contact_click','map_click','reservation_submit'));create policy analytics_read on public.analytics_events for select to authenticated using(private.has_role('super_admin'));
create policy audit_read on public.audit_logs for select to authenticated using(private.has_role('super_admin'));

do $$declare t text;begin foreach t in array array['profiles','restaurant_settings','theme_settings','site_sections','navigation_items','social_links','media','menu_categories','menu_items','gallery_items','special_offers','reservations','seo_settings']loop execute format('create trigger %I before update on public.%I for each row execute function private.touch_updated_at()',t||'_updated_at',t);end loop;end$$;

create trigger audit_user_roles after insert or update or delete on public.user_roles for each row execute function private.audit_row_change();
create trigger audit_settings after insert or update or delete on public.restaurant_settings for each row execute function private.audit_row_change();
create trigger audit_theme after insert or update or delete on public.theme_settings for each row execute function private.audit_row_change();
create trigger audit_sections after insert or update or delete on public.site_sections for each row execute function private.audit_row_change();
create trigger audit_navigation after insert or update or delete on public.navigation_items for each row execute function private.audit_row_change();
create trigger audit_social after insert or update or delete on public.social_links for each row execute function private.audit_row_change();
create trigger audit_media after insert or update or delete on public.media for each row execute function private.audit_row_change();
create trigger audit_categories after insert or update or delete on public.menu_categories for each row execute function private.audit_row_change();
create trigger audit_items after insert or update or delete on public.menu_items for each row execute function private.audit_row_change();
create trigger audit_gallery after insert or update or delete on public.gallery_items for each row execute function private.audit_row_change();
create trigger audit_offers after insert or update or delete on public.special_offers for each row execute function private.audit_row_change();
create trigger audit_reservations after update or delete on public.reservations for each row execute function private.audit_row_change();
create trigger audit_seo after insert or update or delete on public.seo_settings for each row execute function private.audit_row_change();

insert into public.roles(slug,name,description)values('super_admin','مدیر ارشد','دسترسی کامل'),('manager','مدیر رستوران','مدیریت منو و رزرو'),('editor','ویرایشگر','محتوا و رسانه');
insert into public.restaurant_settings(id)values('00000000-0000-0000-0000-000000000001');insert into public.theme_settings(id)values('00000000-0000-0000-0000-000000000002');insert into public.seo_settings(id)values('00000000-0000-0000-0000-000000000003');
insert into public.site_sections(section_key,title,title_en,subtitle,subtitle_en,body,body_en,sort_order,settings)values
('hero','طعم، فراتر از انتظار','Taste beyond expectation','یک تجربه لوکس از غذا، فضا و مهمان‌نوازی.','A refined experience of food, space and hospitality.','','',10,'{"overlay":0.58,"height":"86vh"}'),
('about','داستان نوآر','The NOIR story','جایی که جزئیات، مزه را کامل می‌کنند.','Where details complete the taste.','در نوآر، منوی فصل و طراحی فضا در کنار هم تجربه‌ای دقیق می‌سازند.','At NOIR, seasonal menus and spatial design create a measured experience.',20,'{}'),
('featured','انتخاب سرآشپز','Chef''s selection','غذاهایی برای یک شب به‌یادماندنی.','Dishes for an unforgettable evening.','','',30,'{}'),
('offers','پیشنهادهای ویژه','Special offers','برای لحظاتی که باید متفاوت باشند.','For moments that deserve something different.','','',40,'{}'),
('gallery','فضای نوآر','The NOIR space','از آشپزخانه تا میز، همه‌چیز بخشی از تجربه است.','Every detail is part of the experience.','','',50,'{}'),
('reservation','رزرو میز','Reserve a table','میز خود را برای یک تجربه آرام و خاص رزرو کنید.','Reserve your table for a refined evening.','','',60,'{}'),
('contact','با ما در ارتباط باشید','Get in touch','برای مسیر، رزرو و اطلاعات بیشتر.','For directions, reservations and more.','','',70,'{}'),
('footer','نوآر','NOIR','Taste beyond expectation','','© 2026 NOIR. All rights reserved.','',100,'{}');
insert into public.navigation_items(label,label_en,href,sort_order)values('خانه','Home','/',10),('منو','Menu','/menu',20),('داستان ما','About','#about',30),('گالری','Gallery','#gallery',40),('رزرو','Reservation','#reservation',50),('تماس','Contact','#contact',60);
insert into public.social_links(provider,label,sort_order)values('instagram','Instagram',10),('whatsapp','WhatsApp',20),('telegram','Telegram',30),('facebook','Facebook',40),('tiktok','TikTok',50);
insert into public.menu_categories(id,name,name_en,description,description_en,icon,sort_order)values
('10000000-0000-0000-0000-000000000001','پیش‌غذا','Starters','شروعی سبک و دقیق.','A precise start.','✦',10),('10000000-0000-0000-0000-000000000002','غذاهای اصلی','Mains','امضای آشپزخانه نوآر.','NOIR kitchen signatures.','◆',20),('10000000-0000-0000-0000-000000000003','پاستا','Pasta','تازه و دست‌ساز.','Fresh and handmade.','⌁',30),('10000000-0000-0000-0000-000000000004','استیک','Steak','برش‌های منتخب.','Selected cuts.','◇',40),('10000000-0000-0000-0000-000000000005','دسر','Dessert','پایان شیرین.','A sweet ending.','◌',50),('10000000-0000-0000-0000-000000000006','نوشیدنی','Drinks','نوشیدنی‌های منتخب.','Curated drinks.','☼',60);
insert into public.menu_items(category_id,name,name_en,description,description_en,ingredients,ingredients_en,allergens,tags,price,sort_order,is_available,is_special,is_popular,is_new,is_vegetarian,is_vegan,is_spicy)values
('10000000-0000-0000-0000-000000000001','کارپاچیو گوشت','Beef Carpaccio','برش‌های نازک فیله، روغن زیتون و پارمزان.','Thin beef tenderloin, olive oil and parmesan.','فیله گوساله، پارمزان، روغن زیتون','Beef tenderloin, parmesan, olive oil',ARRAY['لبنیات'],ARRAY['پرفروش'],590000,10,true,false,true,false,false,false,false),
('10000000-0000-0000-0000-000000000001','بورِاتا و گوجه‌های کبابی','Burrata & Charred Tomatoes','بورِاتای تازه با گوجه و ریحان.','Fresh burrata with tomato and basil.','بورِتا، گوجه، ریحان','Burrata, tomato, basil',ARRAY['لبنیات'],ARRAY['گیاهی'],520000,20,true,false,false,false,true,false,false),
('10000000-0000-0000-0000-000000000002','مرغ سوخاری ترافل','Truffle Crispy Chicken','مرغ برشته با سس ترافل.','Crispy chicken with truffle sauce.','مرغ، ترافل، سیب‌زمینی، پارمزان','Chicken, truffle, potato, parmesan',ARRAY['لبنیات'],ARRAY['ویژه'],890000,10,true,true,true,true,false,false,false),
('10000000-0000-0000-0000-000000000002','ریزوتوی قارچ جنگلی','Wild Mushroom Risotto','ریزوتوی خامه‌ای با قارچ و روغن ترافل.','Creamy risotto with wild mushrooms.','برنج، قارچ، پارمزان','Rice, mushrooms, parmesan',ARRAY['لبنیات'],ARRAY['گیاهی'],760000,20,true,false,true,false,true,false,false),
('10000000-0000-0000-0000-000000000003','پاستا آلفردو قارچ','Mushroom Alfredo','پاستای دست‌ساز با قارچ و سس پارمزان.','Handmade pasta with mushrooms and parmesan sauce.','پاستا، قارچ، خامه، پارمزان','Pasta, mushrooms, cream, parmesan',ARRAY['گلوتن','لبنیات'],ARRAY['گیاهی'],690000,10,true,false,false,false,true,false,false),
('10000000-0000-0000-0000-000000000004','ریب‌آی با کره گیاهی','Herb Butter Ribeye','ریب‌آی گریل‌شده با کره گیاهی.','Grilled ribeye with herb butter.','ریب‌آی، کره، فلفل','Ribeye, butter, pepper',ARRAY['لبنیات'],ARRAY['سرآشپز'],1590000,10,true,false,true,false,false,false,true),
('10000000-0000-0000-0000-000000000005','چیزکیک پسته','Pistachio Cheesecake','چیزکیک خامه‌ای با پسته و مرکبات.','Creamy cheesecake with pistachio and citrus.','پنیر، پسته، مرکبات','Cheese, pistachio, citrus',ARRAY['لبنیات','آجیل','گلوتن'],ARRAY['جدید'],450000,10,true,false,false,true,true,false,false),
('10000000-0000-0000-0000-000000000006','اسپرسو تونیک','Espresso Tonic','اسپرسو خنک روی تونیک و یخ.','Chilled espresso over tonic and ice.','اسپرسو، تونیک، یخ','Espresso, tonic, ice',ARRAY[]::text[],ARRAY['گیاهی'],320000,10,true,false,true,false,true,true,false);
insert into public.special_offers(title,title_en,description,description_en,old_price,new_price,starts_at,ends_at)values('منوی دو نفره نوآر','NOIR Set for Two','یک انتخاب کامل برای دو نفر.','A curated set for two.',2200000,1850000,'2026-01-01','2030-01-01');

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)values('restaurant-media','restaurant-media',true,10485760,ARRAY['image/jpeg','image/png','image/webp','image/avif'])on conflict(id)do update set public=true,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
create policy restaurant_media_public_read on storage.objects for select using(bucket_id='restaurant-media');
create policy restaurant_media_staff_insert on storage.objects for insert to authenticated with check(bucket_id='restaurant-media' and private.has_any_role(array['super_admin','manager','editor']));
create policy restaurant_media_staff_update on storage.objects for update to authenticated using(bucket_id='restaurant-media' and private.has_any_role(array['super_admin','manager','editor'])) with check(bucket_id='restaurant-media' and private.has_any_role(array['super_admin','manager','editor']));
create policy restaurant_media_staff_delete on storage.objects for delete to authenticated using(bucket_id='restaurant-media' and private.has_any_role(array['super_admin','manager','editor']));
grant select on all tables in schema public to anon;grant select,insert,update,delete on all tables in schema public to authenticated;grant usage,select on all sequences in schema public to authenticated;grant insert on public.reservations to anon,authenticated;grant insert on public.analytics_events to anon,authenticated;
