-- Reproducible private-schema RPC hardening. Public API remains invoker-only.
create or replace function private.enroll_in_course(p_course_id uuid) returns public.enrollments language plpgsql security definer set search_path=public,pg_temp as $$
declare v_user_id uuid:=auth.uid();v_enrollment public.enrollments;
begin if v_user_id is null then raise exception 'not_authenticated';end if;if not exists(select 1 from public.courses where id=p_course_id and is_published=true) then raise exception 'course_not_available';end if;insert into public.enrollments(course_id,user_id,status) values(p_course_id,v_user_id,'active') on conflict(course_id,user_id) do update set status=case when public.enrollments.status='completed' then 'completed' else 'active' end returning * into v_enrollment;return v_enrollment;end;$$;
revoke all on function private.enroll_in_course(uuid) from public,anon,authenticated;
drop function if exists public.enroll_in_course(uuid);create or replace function public.enroll_in_course(p_course_id uuid) returns public.enrollments language sql security invoker set search_path=public,pg_temp as $$ select private.enroll_in_course(p_course_id); $$;revoke all on function public.enroll_in_course(uuid) from public,anon;grant execute on function public.enroll_in_course(uuid) to authenticated;

create or replace function private.update_lesson_progress(p_lesson_id uuid,p_progress_percent numeric) returns public.lesson_progress language plpgsql security definer set search_path=public,pg_temp as $$
declare v_user_id uuid:=auth.uid();v_progress numeric:=greatest(0,least(100,p_progress_percent));v_row public.lesson_progress;
begin if v_user_id is null then raise exception 'not_authenticated';end if;if not exists(select 1 from public.lessons l join public.course_modules m on m.id=l.module_id join public.enrollments e on e.course_id=m.course_id where l.id=p_lesson_id and l.is_published=true and e.user_id=v_user_id and e.status in('active','completed')) then raise exception 'lesson_not_available';end if;insert into public.lesson_progress(lesson_id,user_id,progress_percent,completed_at) values(p_lesson_id,v_user_id,v_progress,case when v_progress>=100 then now() else null end) on conflict(lesson_id,user_id) do update set progress_percent=excluded.progress_percent,completed_at=excluded.completed_at,updated_at=now() returning * into v_row;return v_row;end;$$;
revoke all on function private.update_lesson_progress(uuid,numeric) from public,anon,authenticated;
drop function if exists public.update_lesson_progress(uuid,numeric);create or replace function public.update_lesson_progress(p_lesson_id uuid,p_progress_percent numeric) returns public.lesson_progress language sql security invoker set search_path=public,pg_temp as $$ select private.update_lesson_progress(p_lesson_id,p_progress_percent); $$;revoke all on function public.update_lesson_progress(uuid,numeric) from public,anon;grant execute on function public.update_lesson_progress(uuid,numeric) to authenticated;

create or replace function private.admin_promote_waitlist(p_program_id uuid) returns table(registration_id uuid,user_id uuid,waitlist_position integer) language plpgsql security definer set search_path=public,pg_temp as $$
declare v_user uuid:=auth.uid();v_capacity integer;v_confirmed integer;v_item public.waitlist_entries%rowtype;
begin if v_user is null then raise exception 'authentication_required';end if;if not public.has_any_role(array['super_admin','program_manager','crm_manager']::public.app_role[]) then raise exception 'forbidden';end if;select capacity into v_capacity from public.programs where id=p_program_id for update;if not found then raise exception 'program_not_found';end if;if v_capacity is null then raise exception 'unlimited_capacity';end if;select count(*)::integer into v_confirmed from public.registrations where program_id=p_program_id and status='confirmed';if v_confirmed>=v_capacity then raise exception 'capacity_full';end if;select w.* into v_item from public.waitlist_entries w join public.registrations r on r.id=w.registration_id where w.program_id=p_program_id and w.promoted_at is null and r.status='waitlisted' order by w.position asc,w.joined_at asc for update of w,r skip locked limit 1;if not found then raise exception 'waitlist_empty';end if;update public.registrations set status='confirmed' where id=v_item.registration_id;update public.waitlist_entries set promoted_at=now() where id=v_item.id;return query select v_item.registration_id,v_item.user_id,v_item.position;end;$$;
revoke all on function private.admin_promote_waitlist(uuid) from public,anon,authenticated;
drop function if exists public.admin_promote_waitlist(uuid);create or replace function public.admin_promote_waitlist(p_program_id uuid) returns table(registration_id uuid,user_id uuid,waitlist_position integer) language sql security invoker set search_path=public,pg_temp as $$ select * from private.admin_promote_waitlist(p_program_id); $$;revoke all on function public.admin_promote_waitlist(uuid) from public,anon;grant execute on function public.admin_promote_waitlist(uuid) to authenticated;

revoke all on function public.award_points(integer,text,text,uuid) from public,anon,authenticated;drop function if exists public.award_points(integer,text,text,uuid);